version: 2
jobs:
  build:
    docker:
      - image: node:7
    steps:
      - checkout
      - run: echo "hello world"
deployment:
  staging:
    branch: master
    heroku:
      appname: comeeda-api
